name: Update Blog Post Embeddings

on:
  # Run when manually triggered from the GitHub Actions tab
  workflow_dispatch:
    inputs:
      post:
        description: 'Path to a specific blog post file (e.g., content/posts/my-post.md)'
        required: false
        default: ''
      skip_kv:
        description: 'Skip updating KV metadata'
        required: false
        default: 'false'
        type: boolean

jobs:
  update-embeddings:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_AI_TOKEN: ${{ secrets.CLOUDFLARE_AI_TOKEN }}
      CLOUDFLARE_VECTORIZE_TOKEN: ${{ secrets.CLOUDFLARE_VECTORIZE_TOKEN }}
      CLOUDFLARE_KV_NAMESPACE_ID: ${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}
      VECTORIZE_INDEX_NAME: ${{ vars.VECTORIZE_INDEX_NAME || 'blog-posts' }}
      PATH_PATTERN: ${{ vars.PATH_PATTERN || 'content/posts' }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Checkout with history to detect changed files
          fetch-depth: 2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests
      
      - name: Process Blog Posts
        run: |
          mkdir -p .github/scripts
          cp $GITHUB_WORKSPACE/.github/scripts/blog_processor.py .github/scripts/blog_processor.py
          
          SKIP_KV_ARG=""
          if [ "${{ github.event.inputs.skip_kv }}" == "true" ]; then
            SKIP_KV_ARG="--skip-kv"
          fi
          
          if [ -n "${{ github.event.inputs.post }}" ]; then
            python .github/scripts/blog_processor.py --post "${{ github.event.inputs.post }}" $SKIP_KV_ARG
          else
            python .github/scripts/blog_processor.py --path-pattern "$PATH_PATTERN" $SKIP_KV_ARG
          fi
        env:
          PYTHONUNBUFFERED: 1
