name: Update Blog Post Embeddings

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      post:
        description: 'Path to a specific blog post file (e.g., posts/my-post.md)'
        required: false
        default: ''

jobs:
  update-embeddings:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_VECTORIZE_TOKEN: ${{ secrets.CLOUDFLARE_VECTORIZE_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Update Embeddings
        run: |
          # If a specific post was provided via workflow_dispatch input, pass it as an argument.
          if [ -n "${{ github.event.inputs.post }}" ]; then
            python scripts/update_embeddings.py --post "${{ github.event.inputs.post }}"
          else
            python scripts/update_embeddings.py
          fi
